### ISSUE TITLE
Where's Source Code?

### ISSUE THREAD

**Issue by jsl303** [JoshMiele/ChartMaker#1]
Thanks for the app.
I just cloned the repo, but there's no source code.
It only has examples and the binary.
Perhaps binary should go into release instead?

**Comment by JoshMiele** [comment]
The binary is just the Microsoft XSLT processor that folks could download elsewhere if they wanted. Not sure if that source is available, but that executable is only included for convenience. The actual "source code" (if you will) is the JAMBRL.XSL file
